### ISSUE TITLE
Fetch Coordinate Frame w/ ExperimentResource

### ISSUE THREAD

**Issue by william-silversmith** [jhuapl-boss/intern#10]
Feature Request. Working on `intern-0.9.4`

Hi guys!

I've been playing around with intern and The BOSS. One feature I'd appreciate is if there was a way to automatically populate the coordinate frame (or at least the name of it) when retrieving an ExperimentResource from a BossRemote. I believe it's currently set to 'foo'. I can manage without it by manually looking up the name of the coordinate frame or directly querying the API but it'd helpful.

The use case here is locating the boundaries for a cutout.

Thanks!
Will

**Comment by movestill** [comment]
Will, I think you're doing something wrong. This isn't the full listing from an `ipython` session, but this demonstrates how to get the coordinate frame name from the experiment:

```
In [12]: exp = ExperimentResource('em', 'kasthuri2015')

In [13]: exp2 = rmt.get_project(exp)

In [14]: exp2.raw
Out[14]:
{'channels': ['cc', 'mem_cv_v1', 'syn_cv_v1'],
 'collection': 'kasthuri2015',
 'coord_frame': 'kasthuri2015_6nm_offset0',
 'creator': 'will',
 'description': '',
 'hierarchy_method': 'anisotropic',
 'name': 'em',
 'num_hierarchy_levels': 1,
 'num_time_samples': 1,
 'time_step': None,
 'time_step_unit': ''}

In [15]: exp2.coord_frame
Out[15]: 'kasthuri2015_6nm_offset0'
```

**Comment by william-silversmith** [comment]
Thank you Tim! I somehow missed that I needed to call get project. Thanks
again. :)
