### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by Niuhao1998** [jhuapl-boss/intern#107]
I run the example code like this:

```
from intern import array
em = array("bossdb://mulcahy2022/15h_L1/em")
data = em[2300:2301, 15000:16024, 12000:13024]
```

However,there are some bugs here.
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Max retries exceeded with url: /bossdb-open-data/mulcahy2022/15h_L1/em/info (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

when I debug the code in intern.
array.py:(1150)self._channel = self.volume_provider.get_channel(
                uri.channel, uri.collection, uri.experiment
            )
the bug is here.
I want to know how to get the data.Thanks

**Comment by j6k4m8** [comment]
Hi @Niuhao1998  — sorry for the delay in getting back to you — it looks like this is an error between your machine and AWS; have you been able to work around this? Happy to help you get set up with some workaround otherwise!
