### ISSUE TITLE
requests Dependency Conflict

### ISSUE THREAD

**Issue by william-silversmith** [jhuapl-boss/intern#16]
| ndio version |  os  | python |
|-----|------|-------|
| *   | Ubuntu 14.04    | 3.4     |

Hi all,

I've integrated intern into a cutout client my lab uses, but the pinned version of requests intern uses conflicts with the one we're using for other purposes. Would it be possible to change `requests==2.11.1`  into `requests>=2.11.1`? We're using version 2.18.4. It's mostly not a problem, but it conflicts with creating dockers for me.

```
Processing dependencies for igneous==0.0.1.dev8
error: requests 2.18.4 is installed but requests==2.11.1 is required by set(['intern'])
```

Thank you for your help!!

**Comment by movestill** [comment]
William, just committed the change to our integration branch. Sorry for the long delay. Was out on vacation and busy with other projects.
