### ISSUE TITLE
Install blosc (optionally)

### ISSUE THREAD

**Issue by j6k4m8** [jhuapl-boss/intern#5]
When pip-installing intern, blosc must be installed first or the install fails. I wonder if there's a way to automate this (optionally), or perhaps check for blosc on the system before continuing.

Either way, should be documented [here](https://github.com/jhuapl-boss/intern/wiki/Boss%20Setup%20Tutorial)

**Comment by dkleissa** [comment]
Right now installing blosc optionally seems like a deal-breaker as the primary interface to get cutouts is blosc.

Does the install actually fail, or are you seeing the c-bindings fail to build and pip still installs successfully? I'm pretty sure it'll fall back on a slower python implementation?

**Comment by j6k4m8** [comment]
Install fails, at least on 16.04 Ubuntu (n=1). I'll try a few other
machines to see if the problem is intern or if it's the machine.

**Comment by dkleissa** [comment]
Ok. Possibly a 16.04 issue, have not tested that. Provide more details if possible.
