### ISSUE TITLE
incorrect data type for chunked cutouts

### ISSUE THREAD

**Issue by alexbaden** [jhuapl-boss/intern#6]
When pulling a chunked cutout, a new `ndarray` is created and each resultant chunk is merged into the array as the chunk resolves (see https://github.com/jhuapl-boss/intern/blob/master/intern/service/boss/v1/volume.py#L136). However, by not setting a datatype on the array, a default datatype of `float64` is apparently being used. Even though each chunk has the correct datatype, the resultant datatype is `float64` and float64 data ends up being returned to the end user.

**Comment by dkleissa** [comment]
@j6k4m8 - Can you double check this? Previous PR added chunking automatically to all cutout requests, right? If so, need to patch ASAP. Should check the datatype of the channel being used and create a numpy array of that type.

**Comment by j6k4m8** [comment]
I'll review this evening. Gonna include a check for dtype in the tests too, since it didn't complain about this and should have.

**Comment by j6k4m8** [comment]
@alexbaden Were you setting a dtype on the ChannelResource?

**Comment by alexbaden** [comment]
Yup. All of my blocks have the correct data type. The problem is result is
declared without a data type, so it gets the default of float64. Then each
block is cast to float64 when added.

**Comment by j6k4m8** [comment]
This is fixed in #17, and you get the fix for free if you use `BossRemote#get_channel` too.
