### ISSUE TITLE
Don't upload blank cuboids

### ISSUE THREAD

**Issue by j6k4m8** [jhuapl-boss/intern#65]
I _thiiiink_ (@dxenes1 can probably correct me if I'm wrong) that there's no reason to `create_cutout` any subvolume comprised solely of zeros. In other words, we could add the following to `intern.service.boss.v1.volume` `VolumeService#create_cutout`:

```python
if np.sum(numpyVolume) == 0:
    return
```

I tested this on a recent data move and didn't seem to suffer any performance issues (and obviously sped up the process quite dramatically).

@movestill @dxenes1 can you think of any reason why we wouldn't want to merge that into master? Am I forgetting something?

**Comment by dxenes1** [comment]
AFAIK This should be okay! My cutout_to_black goes through a different code "route" so adding those lines to create_cutout shouldn't break anything.

**Comment by movestill** [comment]
Agree, this should be fine.
