### ISSUE TITLE
Push missing git tags

### ISSUE THREAD

**Issue by stuarteberg** [jhuapl-boss/intern#81]
[The PyPI release history][1] for `intern` includes releases that are not [tagged in this git repository.][2]

Can you please push the tags for releases for `v1.1.0`, `v1.1.1`, and `v1.2.0`?  Once you do, I can update the [intern feedstock][3] on conda-forge.

[1]: https://pypi.org/project/intern/#history

[2]: https://github.com/jhuapl-boss/intern/releases

[3]: https://github.com/conda-forge/intern-feedstock/blob/master/recipe/meta.yaml

**Comment by j6k4m8** [comment]
Thank you a ton for bringing this up! These should be pushed now; let me know if this works on your end?

**Comment by stuarteberg** [comment]
Looks good.  I'll wait for the conda-forge bot to notice the change.  It ought to generate a PR that will auto-update the recipe.  BTW, would you like to be added as a "maintainer" for that feedstock?  Then you'll be able to click "merge" when the bot updates the recipe next time.

**Comment by j6k4m8** [comment]
@stuarteberg thanks so much! 
> would you like to be added as a "maintainer" for that feedstock? 

that would be great! perhaps good to add @dxenes1, @sandyhider, and @movestill as well, if it's easy?

**Comment by stuarteberg** [comment]
For some reason the bot didn't notice the new tags, so I created the PR myself ([here][1]).  Hopefully the bot kicks in next time; it saves mundane work in most cases.

[1]: https://github.com/conda-forge/intern-feedstock/pull/6

The PR passed and the new package is uploaded:
https://anaconda.org/conda-forge/intern/files

>perhaps good to add @dxenes1, @sandyhider, and @movestill as well, if it's easy?

Done.  Now you should all have invitations from github to join the maintainer team for the intern "feedstock" repo.  I notice you already accepted yours.

**Comment by j6k4m8** [comment]
This is great, thank you so much Stuart!
