### ISSUE TITLE
Where does Windows config file live?

### ISSUE THREAD

**Issue by j6k4m8** [jhuapl-boss/intern#95]
@sandyhider @hannahgooden have you found the best place to put an intern config file on your Windows machines in the past?

**Comment by movestill** [comment]
Wouldn't it be `c:\Users\user-name\.intern`?

**Comment by hannahgooden** [comment]
Unfortunately I am the wrong person to ask, I just use WSL.

**Comment by j6k4m8** [comment]
I just updated the docs, thanks all!
