### ISSUE TITLE
Optional cloudvolume dependency is not optional

### ISSUE THREAD

**Issue by im-a-jin** [jhuapl-boss/intern#98]
| intern version |  os  | python |
|----------------|------|--------|
| 1.3.1 | MacOS Monterey 12.3 | 3.7.13, 3.8.9 |

`import intern` fails with `ModuleNotFoundError: No module named 'cloudvolume'` when installing intern into a new virtual environment.

**Comment by j6k4m8** [comment]
Thank you for reporting! We will address in the next update, and I'll add updates here as we go.

**Comment by im-a-jin** [comment]
Any updates on this issue? My current workaround involves manually pinning a set of dependencies, but I'm not sure if that's the best way to address this problem.

**Comment by j6k4m8** [comment]
This should be fixed in 1.3.3 on pypi (`pip install -U intern`) — can you confirm @im-a-jin ?

**Comment by im-a-jin** [comment]
It works for me locally and on colab. Thank you!

**Comment by j6k4m8** [comment]
Awesome! Super glad to hear it's working now :)
