### ISSUE TITLE
from intern import array not working on macOS Chip Apple M1 Pro

### ISSUE THREAD

**Issue by itsJorgeRivera** [jhuapl-boss/intern#99]
| intern (not obtainable, but latest version as of 10/10/22) |  macOS Monterrey  | python3.10.7|

<img width="1192" alt="Screen Shot 2022-10-10 at 2 46 03 PM" src="https://user-images.githubusercontent.com/115184427/195201748-0e62f50a-b23c-4f82-8cba-42e3bbe29a4c.png">
Fresh install of intern on a virtual environment per tutorial instructions. The above message is what I receive when trying to find my version of intern or import array.

**Comment by itsJorgeRivera** [comment]
I've tried downgrading to previous versions of zfpy, but this does not change anything.

**Comment by j6k4m8** [comment]
Thanks for reporting, @itsJorgeRivera! Can you share a complete traceback (is that the whole error message?) of that error and we'll take a look? I don't have an Apple Si laptop but will find someone on the team who does!

**Comment by itsJorgeRivera** [comment]
Thanks for getting back to me so quickly! I've attached a screenshot of my terminal after running `from intern import array` to show the full error message chain. 
![Screen Shot 2022-10-12 at 11 10 37 AM](https://user-images.githubusercontent.com/115184427/195380811-1466ae2c-edb6-454e-a05e-940554166ca2.png)

**Comment by itsJorgeRivera** [comment]
Sounds great, thanks! 

I've tried downgrading my python to 3.9 in the virtual env but Cloud-volume wont install with a legacy version 😞 , so that gets stopped there.

**Comment by itsJorgeRivera** [comment]
With the removal of cloudvolume, this is looking good. Thank you Jordan! 
![Figure_1](https://user-images.githubusercontent.com/115184427/197614562-f99dbf9b-c954-48f5-a9c9-58f64d429e1c.png)

**Comment by j6k4m8** [comment]
Super awesome!! Glad it's working for you :)

**Comment by jasper-tms** [comment]
fyi, @william-silversmith provided wheels for zfpy that work on M1 mac over [here](https://github.com/seung-lab/cloud-volume/issues/561#issuecomment-1336280521), which should resolve this issue if you do want to get cloudvolume working on your M1 mac.

**Comment by BrockWester** [comment]
Jasper - thanks for sending, much appreciated! (and thanks @william-silversmith!)
